name: ci
on:
  pull_request:
  push:
    branches:
      - master
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: |
          zig build -Doptimize=Debug
          zig build -Doptimize=ReleaseSafe
      - name: Tests
        run: |
          zig build test --summary all

  x86_64-windows:
    runs-on: windows-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: |
          zig build -Doptimize=Debug
          zig build -Doptimize=ReleaseSafe
      - name: Tests
        run: |
          zig build test --summary all
  x86_64-macos:
    runs-on: macos-latest
    env:
      ARCH: "x86_64"
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: |
          zig build -Doptimize=Debug
          zig build -Doptimize=ReleaseSafe
      - name: Tests
        run: |
          zig build test --summary all
  aarch64-macos:
    runs-on: macos-latest
    env:
      ARCH: "aarch64"
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build
        run: |
          zig build -Doptimize=Debug
          zig build -Doptimize=ReleaseSafe
      - name: Tests
        run: |
          zig build test --summary all
